### ISSUE TITLE
The layout not like on the original page

### ISSUE THREAD

**Issue by NiiazalyDzhumaliev** [JelilFaisalAbudu/teardown#1]
Check the original website

**Comment by fdfragoso** [comment]
The features asked for this project isn't to clone, but to create a heatmap to understand UX design. So the layout shouldn't be the same. The groups who clone it had to change it. 
I suggest checking the Odin project task: https://www.theodinproject.com/courses/html5-and-css3/lessons/design-teardown
Solutions on the Odin project: https://ikraamg.github.io/Design-Teardown-Heatmap/
